name: Build Mac Trackpad Mapper

on:
  workflow_dispatch: # Allows you to manually trigger the build with a button

jobs:
  build:
    runs-on: macos-latest # This forces GitHub to use a real Mac virtual machine

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Compile Application
      run: |
        make release

    - name: Upload Finished App Bundle
      uses: actions/upload-artifact@v4
      with:
        name: Custom-Mac-Trackpad-Mapper
        path: build/
